version: "2.2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  redis-dump:
    image: aiziyuer/redis-dump:0.4.0
    build:
      context: ./redis-dump
      args:
        version: "0.4.0"
