version: '2'

services:
    client:
      build: ./client
      privileged: true
      environment:
       - WHITELIST_IP=31.31.31.0/24
      links:
       - server
      volumes:
       - ./client/etc/systemd/system/container-environment-inject.service:/etc/systemd/system/container-environment-inject.service
       - ./client/etc/systemd/system/redsocks-iptables.service:/etc/systemd/system/redsocks-iptables.service
       - ./client/etc/systemd/system/redsocks.service:/etc/systemd/system/redsocks.service
    server:
      hostname: server
      build: ./server
      privileged: true
      expose:
       - 1080