---

# 测试ansible
# ansible-playbook -i inventory/development/hosts.ini 00-prepare.yml

# 修改通用源
- hosts: all:k8s-cluster:etcd
  gather_facts: true
  roles:
     -  { role: basic }
     
# 安装docker等必要的软件
- hosts: k8s-cluster
  gather_facts: no
  roles:
     -  { role: docker }