version: '2'

services:
    
    redis:
      container_name: redis
      build: ./redis
      #privileged: true
      volumes:
       - ./configuation/redis/etc/redis.conf:/etc/redis.conf
       - ./configuation/redis/usr/lib/systemd/system/redis.service:/usr/lib/systemd/system/redis.service
       - ./run/var/lib/redis:/var/lib/redis:z
      ports:
       - 16379:6379
      environment:
       - DEBUG=aiziyuer
    
    openresty:
      container_name: openresty
      build: ./openresty
      #privileged: true
      volumes:
       - ./configuation/openresty/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      ports:
       - 10080:80
      environment:
       - DEBUG=aiziyuer
    