version: '2'

services:
    
    redis:
      container_name: redis
      build: ./redis
      privileged: true
      volumes:
       - ./run/var/lib/redis:/var/lib/redis:z
      environment:
       - DEBUG=aiziyuer
    
    nginx:
      container_name: nginx
      build: ./nginx
      privileged: true
      environment:
       - DEBUG=aiziyuer
    