version: '2.1'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: harbor
      POSTGRES_PASSWORD: harbor
      POSTGRES_USER: harbor
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432/tcp"
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data:z
  redis:
    image: redis
    