version: '2'

services:
    default:
      build: ./centos7
      privileged: true
      volumes:
       - ./conf/default/nginx.conf:/etc/nginx/nginx.conf
    http:
      build: ./centos7
      privileged: true
      volumes:
       - ./conf/http/nginx.conf:/etc/nginx/nginx.conf
    socket:
      build: ./centos7
      privileged: true
      volumes:
       - ./conf/socket/nginx.conf:/etc/nginx/nginx.conf