version: '2'

services:
 
    # 测试用的服务
    nginx:
      image: nginx:1.17.2-alpine-perl
      expose:
       - "80"
    
    redis:
      image: redis:alpine3.10
      user: root
      entrypoint: 
        - redis-server
        - /usr/local/etc/redis/redis.conf
      volumes:
       - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
       - ./data/redis:/var/lib/redis:z
       - ./data/redis/log:/var/log/redis/:z
      ports:
       - "6379:6379/tcp"
    
    openresty:
      image: openresty/openresty:1.15.8.1-3-alpine
      volumes:
       - ./conf/openresty/conf.d:/etc/nginx/conf.d
       - ./data/openresty/logs:/usr/local/openresty/nginx/logs
      ports:
       - "80:80/tcp"
       - "443:443/tcp"
      links:
       - "redis"
       - "nginx"

