version: '2'

services:
 
    # 测试用的服务
    nginx:
      container_name: nginx
      build: ./nginx
      #privileged: true
      ports:
       - 20080:80
    
    redis:
      container_name: redis
      build: ./redis
      #privileged: true
      volumes:
       - ./conf/redis/redis.conf:/etc/redis.conf
       - ./conf/redis/redis.service:/usr/lib/systemd/system/redis.service
       - ./data/redis:/var/lib/redis:z
      ports:
       - 16379:6379
    
    openresty:
      container_name: openresty
      build: ./openresty
      #privileged: true
      volumes:
       - ./conf/openresty/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf
       - ./data/openresty/logs:/usr/local/openresty/nginx/logs
      ports:
       - 10080:80
      links:
       - "redis"
       - "nginx"

