---
- name: install docker on CentOS-7
  yum: 
    name: "docker"
    state: latest
  when: ansible_distribution == 'CentOS' and ansible_distribution_version|int >= 7

- name: install docker on EulerOS
  yum: 
    name: "docker-engine"
    state: latest
  when: ansible_distribution == 'EulerOS'
