version: '2'

services:
    client:
      build: ./client
      privileged: true
      environment:
       - WHITELIST_IP=31.31.0.0/16
      links:
       - server
    server:
      hostname: server
      build: ./server
      privileged: true