version: '2'

services:
    centos7-sshd-aarch64:
      build: ./centos7-sshd-aarch64
      ports:
        - "2022:22"
      volumes:
        - ./data:/data
      privileged: true
    euler2.3-sshd-aarch64:
      build: ./euler2.3-sshd-aarch64
      ports:
        - "2122:22"
      volumes:
        - ./data:/data
      privileged: true