---

- name: nginx
  when:
   - ansible_os_family == "RedHat"
  yum:
    state: present
    name:
     - nginx

- name: enable and start nginx
  systemd:
    name: nginx
    daemon_reload: yes
    state: started
    enabled: yes

- name: reload nginx
  shell:
    cmd: |
      nginx -s reload