version: '2'

networks:
  gateway-net:
    ipam:
      driver: default
      config:
        - subnet: "11.11.11.0/24"

services:
 
    # 测试用的服务
    example:
      image: nginx:1.17.2-alpine-perl
      networks:
        gateway-net:
          ipv4_address: 11.11.11.101
      expose:
       - "80"
    
    redis:
      image: redis:alpine3.10
      user: root
      entrypoint: 
        - redis-server
        - /usr/local/etc/redis/redis.conf
      networks:
        gateway-net:
          ipv4_address: 11.11.11.3
      volumes:
       - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
       - ./data/redis:/var/lib/redis:z
       - ./data/redis/log:/var/log/redis/:z
      ports:
       - "6379:6379/tcp"
    
    openresty:
      image: openresty/openresty:1.15.8.1-3-alpine
      environment:
        - PROJECT_MODE=DEV
      volumes:
       - ./conf/openresty/conf.d:/etc/nginx/conf.d
       - ./data/openresty/logs:/usr/local/openresty/nginx/logs
      networks:
        gateway-net:
      ports:
       - "80:80/tcp"
       - "443:443/tcp"
      links:
       - "redis"
