version: '2'

services:
    slave:
      build: ./slave
      privileged: true
      volumes:
      - ./conf/kubernetes.repo:/etc/yum.repos.d/kubernetes.repo
      - ./data/mirrors/kubernetes:/mirrors/kubernetes:z
      - ./conf/nginx.conf:/etc/nginx/nginx.conf