version: '2'

services:

    snat:
      build: ./centos7
      privileged: true
      expose:
       - 22
      networks:
        controller:
          ipv4_address: 192.168.1.5
      ports:
       - "20022:22"
 
    master:
      build: ./centos7-with-docker
      privileged: true
      networks:
        controller:
          ipv4_address: 192.168.1.2
      volumes:
       - ./data/master:/var/lib/docker
      expose:
       - 22
       - 6443
           
    gateway:
      build: ./centos7-with-docker
      privileged: true
      networks:
        controller:
          ipv4_address: 192.168.1.4
      volumes:
       - ./data/gateway:/var/lib/docker
      expose:
       - 22
       - 80
       - 6379

    storage:
      build: ./centos7
      networks:
        controller:
          ipv4_address: 192.168.1.3
      privileged: true
      expose:
       - 22
       
    node:
      build: ./centos7-with-docker
      privileged: true
      volumes:
       - ./data/node:/var/lib/docker
      networks:
        node:
          ipv4_address: 192.168.2.2
      expose:
       - 22
       
    ansible:
      build: ./ansible
      volumes:
       - ./conf/ansible-playbook-v2:/ansible-playbook
      working_dir: /ansible-playbook
      networks:
        - controller
        - node
       
networks:
  controller:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
  node:
    ipam:
      driver: default
      config:
        - subnet: "192.168.2.0/24"     